version: "3.8"
services:
  Image1:
    build: .
    container_name: test_in_container_1
    image: test_in_image_1
    environment:
      - "Container1=${Container1}"
    command: bash -c "($Replica1) & tail -F /dev/null"
    volumes:
      - test-results:/app/allure-results/

  Image2:
    build: .
    container_name: test_in_container_2
    image: test_in_image_2
    environment:
      - "Container2=${Container2}"
    command: bash -c "($Replica2) & tail -F /dev/null"
    volumes:
      - test-results:/app/allure-results/

  allure:
    image: "frankescobar/allure-docker-service"
    depends_on:
      - Image1
      - Image2
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - test-results:/app/allure-results

volumes:
  test-results: